mysql_root_password: "{{ vault_mysql_root_password }}" # Define this variable in group_vars/staging/vault.yml

project_root: /www/example_123/public
www_root: /www/example_123/public
web_user: example
web_group: www-data
